

import Banner from "./Componentes/Banner/Banner";
import "./globals.css";
import Footer from "@/app/Componentes/Footer/Footer";

export const metadata = {
title: "Festere",
description: "Generated by create next app",

};

export default function RootLayout({children}){
    return(
        <html lang="pt-br">
        <body>
            
            {children}
            <Footer />
            </body>
        </html>
    );

}